name: .NET Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Build
      run: dotnet publish -r win-x64 -f net8.0 OpenGM/OpenGM.csproj
      
    - name: Archive binaries
      uses: actions/upload-artifact@v4
      with:
        name: release-win-x64
        path: ./OpenGM/bin/win-x64/publish/*
